### ISSUE TITLE
API: User login with email and password

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/quizard-users#2]
**Is your feature request related to a problem? Please describe.**
Currently, the user login functionality requires developers to manually handle the login process and implement the necessary authentication logic. It would be beneficial to have a dedicated API endpoint specifically for user login that accepts the user's email and password as parameters. This will provide a standardized and secure approach to handle user authentication.

**Describe the solution you'd like**
I would like to create a new API endpoint for user login that accepts the user's email and password as parameters. This API endpoint should handle the authentication process securely, including the necessary validations, password hashing, and authentication checks. By having a dedicated API endpoint for user login, developers can easily integrate the login functionality into their applications without the need for extensive authentication implementation.

**Describe alternatives you've considered**
One alternative would be to rely on third-party authentication services or frameworks that provide pre-built login functionality. However, this may introduce dependencies and limit customization options for certain applications. Having an in-house login API gives developers more control over the authentication process and allows for tailored integration.

**Additional context**
By introducing a dedicated API endpoint for user login, we can provide a standardized and secure method for authenticating users. This enhancement will simplify the login integration process, improve security measures such as password hashing, and allow for further customization and extension of the login functionality. Additionally, having a well-defined login API will facilitate future enhancements and integrations with other authentication mechanisms.

**Comment by bontusss** [comment]
Assign me

**Comment by CeoFred** [comment]
@bontusss let me know when you are ready to work on this.

**Comment by bontusss** [comment]
Okay
