### ISSUE TITLE
GoogleAuthCallback & GithubAuthCallback endpoint returning json response on error

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/quizard-users#5]
**Describe the bug**
Currently, the GoogleAuthCallback and GithubAuthCallback endpoints in our application are not functioning as expected when an error occurs during the authentication process. Instead of redirecting the user to the client URL with an error message, they are returning a JSON response.

**To Reproduce**
1. Go to the google auth url, usually http://localhost:3006/api/v1/auth/google
2. using the url in the json response, navigate to the google authentication screen
3. Sign in
4. Make the app just error in anyway

When an error occurs during the authentication process, the GoogleAuthCallback and GithubAuthCallback endpoints should redirect the user to the client URL specified, appending an error message in the query parameters. For example: https://client-url.com?error=authentication_failed or use headers.

Actual Behavior:
Instead of redirecting to the client URL, the GoogleAuthCallback and GithubAuthCallback endpoints are returning a JSON response containing the error details. This behavior is not consistent with the expected behavior.

**Additional context**

**Comment by opensaucerer** [comment]
Currently saying from the context of what I see here...the idea I'm presuming is that the backend handles the entire authentication process (communicating with Google and generating auth URLs) except for after the redirect occurs. I see this convention as the most common amongst users but Google does not really specify how one should go about this. 

Ideally, the only specification Google has is that, if your application has a backend, then you just need to provide it with the `ID token` cos that's essentially everything needed in the end. As opposed to re-inventing the wheel of auth URL generation etc, what I always advise is for the FE to do the entire gymnastics, it's very straightforward thanks to the Firebase SDK. And once the auth is done, the Firebase SDK returns the auth user to the FE and the FE can call `Firebase.User.getIdToken()` to retrieve the ID and send it over to the BE, and from there on, the BE can verify that the token is valid using Google Auth Library and check if one of such already exists in the database. If one exists, a session (JWT) is generated afterward, however, if none exists, an account and a session are generated. 

### Resources
https://developers.google.com/identity/sign-in/web/backend-auth
https://cloud.google.com/run/docs/authenticating/end-users

**Comment by ShowBaba** [comment]
this sounds ok, but I'll need to discuss with the FE team. @CeoFred what's your thoughts on this?

**Comment by CeoFred** [comment]
@opensaucerer , thanks for this insight.. actually never crossed my mind about this approach.. @ShowBaba , the FE team has not started integration. We should discuss this further. From this, we have one less endpoint, not much of a problem but fair enough. I also believe this would be a better UX imo
